services:
  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   restart: always
  #   ports:
  #     - 1000:9090
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - graph-network

  prometheus_to_graph:
    container_name: prometheus_to_graph
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - graph-network
    ports:
      - 5000:5000
    # depends_on:
    #   - prometheus

networks:
  graph-network:
    driver: bridge